apiVersion: v1 
kind: Service 
metadata: 
  name: mongodb-service 
spec: 
  type: LoadBalancer 
  ports: 
    - port: 3306 
  selector: 
    app: mongodb 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongodb-deployment 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mongodb 
  template: 
    metadata: 
      labels: 
        app: mongodb 
    spec: 
      containers: 
        - image: bitnami/mongodb 
          name: mongodb 
          env: 
            - name: MONGODB_ROOT_PASSWORD 
              value: password 
            - name: MONGODB_ROOT_USER 
              value: user 
            - name: MONGODB_PASSWORD 
              value: sofe4790u 
            - name: MONGODB_DATABASE 
              value: myDB 
          ports: 
            - containerPort: 3306 
              name: mongodb 